const mongoose = require('mongoose')

let dbmodel = mongoose.Schema({
    title: String,
    category: { type: Number },
    site: String,
    link: String,
    address: String,
    price: String,
    newprice:String,
    area: { type: Number },
    description: String,
    house_type: String,
    house_direc: String,
    house_balcony: String,
    house_project: String,
    facade: { type: Number },
    road_house: { type: Number },
    lon: { type: String },
    lat: { type: String },
    num_floor: { type: Number },
    num_bed: { type: Number },
    num_bath: { type: Number },
    num_living: { type: Number },
    furniture: String,
    juridical: String,
    width: { type: Number },
    length: { type: Number },
    the_building: String,

    list_img: {
        type: Array,
        default: []
    },
    status: Number,
    hospital: Number,
    clinic: Number,
    pharmacy: Number,
    kindergarten: Number,
    school: Number,
    university: Number,
    college: Number,
    mall: Number,
    supermarket: Number,
    convenience: Number,
    cafe: Number,
    parking: Number,
    bus_station: Number,
    police: Number,
    bank: Number,
    marketplace: Number,
    zoo: Number,
    medical_supply: Number,

})
module.exports = mongoose.model('data', dbmodel, 'data'); 